security:
  oauth2:
    client:
      clientId: <insert your client id> 
      clientSecret: <insert your client secret>
      accessTokenUri: https://<insert your open id hostname>/oidc/token
      userAuthorizationUri: https://<insert your open id hostname>/oidc/authorize
      tokenName: oauth_token
      scope: bona_fide_status, openid 
    resource:
      userInfoUri: https://<insert your open id hostname>/oauth/rpc/json/oidcManager/userinfo
#sample #1
querySamples:
  assemblyId1: GRCh37
  start1: 16358147
  startMin1: 
  startMax1: 
  end1: 
  endMin1: 
  endMax1: 
  referenceName1: 1
  referenceBases1: T
  alternateBases1: C
  variantType1: 
  datasetIds1: 
#sample #2
  assemblyId2: GRCh37
  start2: 
  startMin2: 13035404
  startMax2: 13035410
  end2: 
  endMin2: 13379464
  endMax2: 13379468
  referenceName2: 1
  referenceBases2: N
  alternateBases2: 
  variantType2: DEL
  datasetIds2: EGAD00000000028
#sample #3
  assemblyId3: GRCh37
  start3: 120117469
  startMin3: 
  startMax3: 
  end3: 120117910
  endMin3: 
  endMax3: 
  referenceName3: X
  referenceBases3: N
  alternateBases3: 
  variantType3: DUP
  datasetIds3: 
  
#1) curl "localhost:9075/elixirbeacon/v04/beacon/query?referenceName=1&start=16358147&referenceBases=T&alternateBases=C&assemblyId=GRCh37&includeDatasetResponses=NONE"
#2) curl "localhost:9075/elixirbeacon/v04/beacon/query?referenceName=1&startMin=13035404&startMax=13035410&endMin=13379464&endMax=13379468&referenceBases=N&variantType=DEL&assemblyId=GRCh37&datasetIds=EGAD00000000028&includeDatasetResponses=HIT"
#3) curl "localhost:9075/elixirbeacon/v04/beacon/query?referenceName=X&start=120117469&end=120117910&referenceBases=N&variantType=DUP&assemblyId=GRCh37"
