security:
  oauth2:
    client:
      clientId: <insert your client id> 
      clientSecret: <insert your client secret>
      accessTokenUri: https://<insert your open id hostname>/oidc/token
      userAuthorizationUri: https://<insert your open id hostname>/oidc/authorize
      tokenName: oauth_token
      scope: bona_fide_status, openid 
    resource:
      userInfoUri: https://<insert your open id hostname>/oauth/rpc/json/oidcManager/userinfo
#sample #1
querySamples:
  assemblyId1: GRCh37
  start1: 14929
  startMin1: 
  startMax1: 
  end1: 
  endMin1: 
  endMax1: 
  referenceName1: 1
  referenceBases1: A
  alternateBases1: C
  variantType1: 
  datasetIds1: 
#sample #2
  assemblyId2: GRCh37
  start2: 
  startMin2: 153592310
  startMax2: 153592317
  end2: 
  endMin2: 153517030
  endMax2: 153517050
  referenceName2: X
  referenceBases2: N
  alternateBases2: 
  variantType2: DEL
  datasetIds2: EGAD00000000028
#sample #3
  assemblyId3: GRCh37
  start3: 147880925
  startMin3: 
  startMax3: 
  end3: 146342284
  endMin3: 
  endMax3: 
  referenceName3: X
  referenceBases3: N
  alternateBases3: 
  variantType3: DUP
  datasetIds3: EGAD00000000028
  
#1) curl "localhost:9075/elixirbeacon/v04/beacon/query?referenceName=1&start=14929&referenceBases=A&alternateBases=G&assemblyId=GRCh37"
#2) curl "localhost:9075/elixirbeacon/v04/beacon/query?referenceName=X&startMin=153592310&startMax=153592317&endMin=153517030&endMax=153517050&variantType=DEL&referenceBases=N&assemblyId=GRCh37&datasetIds=EGAD00000000028"
#3) curl "localhost:9075/elixirbeacon/v04/beacon/query?referenceName=X&start=147880925&end=146342284&referenceBases=N&variantType=DUP&assemblyId=GRCh37&datasetIds=EGAD00000000028"
