-- Primary Categories
INSERT INTO consent_code_table(id, name, abbr, description, additional_constraint_required, category_id) VALUES (1, 'No restrictions', 'NRES', 'No restrictions on data use.', false, 1);
INSERT INTO consent_code_table(id, name, abbr, description, additional_constraint_required, category_id) VALUES (2, 'General research use and clinical care', 'GRU(CC)', 'For health/medical/biomedical purposes, including the study of population origins or ancestry.', false, 1);
INSERT INTO consent_code_table(id, name, abbr, description, additional_constraint_required, category_id) VALUES (3, 'Health/medical/biomedical research and clinical care', 'HMB(CC)', 'Use of the data is limited to health/medical/biomedical purposes; does not include the study of population origins or ancestry.', false, 1);
INSERT INTO consent_code_table(id, name, abbr, description, additional_constraint_required, category_id) VALUES (4, 'Disease-specific research and clinical care', 'DS-[XX](CC)', 'Use of the data must be related to [disease].', true, 1);
INSERT INTO consent_code_table(id, name, abbr, description, additional_constraint_required, category_id) VALUES (5, 'Population origins/ancestry research', 'POA', 'Use of the data is limited to the study of population origins or ancestry.', false, 1);
-- Secondary Categories
INSERT INTO consent_code_table(id, name, abbr, description, additional_constraint_required, category_id) VALUES (6, 'Oher research-specific restrictions', 'RS-[XX]', 'Use of the data is limited to studies of [research type] (e.g., pediatric research).', true, 2);
INSERT INTO consent_code_table(id, name, abbr, description, additional_constraint_required, category_id) VALUES (7, 'Research use only', 'RUO', 'Use of data is limited to research purposes (e.g., does not include its use in clinical care).', false, 2);
INSERT INTO consent_code_table(id, name, abbr, description, additional_constraint_required, category_id) VALUES (8, 'No “general methods” research', 'NMDS', 'Use of the data includes methods development research (e.g., development of software or algorithms) ONLY within the bounds of other data use limitations.', false, 2);
INSERT INTO consent_code_table(id, name, abbr, description, additional_constraint_required, category_id) VALUES (9, 'Genetic studies only', 'GSO', 'Use of the data is limited to genetic studies only (i.e., no “phenotype-only” research).', false, 2);
-- Requirements
INSERT INTO consent_code_table(id, name, abbr, description, additional_constraint_required, category_id) VALUES (10, 'Not-for-profit use only', 'NPU', 'Use of the data is limited to not-for-profit organizations.', false, 3);
INSERT INTO consent_code_table(id, name, abbr, description, additional_constraint_required, category_id) VALUES (11, 'Publication required', 'PUB', 'Requestor agrees to make results of studies using the data available to the larger scientific community.', false, 3);
INSERT INTO consent_code_table(id, name, abbr, description, additional_constraint_required, category_id) VALUES (12, 'Collaboration required', 'COL-[XX]', 'Requestor must agree to collaboration with the primary study investigator(s).', true, 3);
INSERT INTO consent_code_table(id, name, abbr, description, additional_constraint_required, category_id) VALUES (13, 'Ethics approval required', 'IRB', 'Requestor must provide documentation of local IRB/REC approval.', false, 3);
INSERT INTO consent_code_table(id, name, abbr, description, additional_constraint_required, category_id) VALUES (14, 'Geographical restrictions', 'GS-[XX]', 'Use of the data is limited to within [geographic region].', true, 3);
INSERT INTO consent_code_table(id, name, abbr, description, additional_constraint_required, category_id) VALUES (15, 'Publication moratorium/embargo', 'MOR-[XX]', 'Requestor agrees not to publish results of studies until [date].', true, 3);
INSERT INTO consent_code_table(id, name, abbr, description, additional_constraint_required, category_id) VALUES (16, 'Time limits on use', 'TS-[XX]', 'Use of data is approved for [x months].', true, 3);
INSERT INTO consent_code_table(id, name, abbr, description, additional_constraint_required, category_id) VALUES (17, 'User-specific restrictions', 'US', 'Use of data is limited to use by approved users.', false, 3);
INSERT INTO consent_code_table(id, name, abbr, description, additional_constraint_required, category_id) VALUES (18, 'Project-specific restrictions', 'PS', 'Use of data is limited to use within an approved project.', false, 3);
INSERT INTO consent_code_table(id, name, abbr, description, additional_constraint_required, category_id) VALUES (19, 'Institution-specific restrictions', 'IS', 'Use of data is limited to use within an approved institution.', false, 3);
